In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
#1.examples using TensorFlow
#scalar tensor
t1 = tf.constant(4)
print("Scalar Tensor: ")
print(t1)

Scalar Tensor: 
tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#vector tensor
t2 = tf.constant([1,5,10,15,20,25])
print("Vector Tensor: ")
print(t2)

Vector Tensor: 
tf.Tensor([ 1  5 10 15 20 25], shape=(6,), dtype=int32)


In [4]:
#matrix tensor
t3 = tf.constant([[1,5], [10,15], [20,25]])
print("Matrix Tensor: ")
print(t3)

Matrix Tensor: 
tf.Tensor(
[[ 1  5]
 [10 15]
 [20 25]], shape=(3, 2), dtype=int32)


In [5]:
#3D tensor
t4 = tf.constant([[[1,5], [10,15]], [[20,25], [30,35]]])
print("3D Tensor: ")
print(t4)

3D Tensor: 
tf.Tensor(
[[[ 1  5]
  [10 15]]

 [[20 25]
  [30 35]]], shape=(2, 2, 2), dtype=int32)


In [6]:
#zeros tensor
t5 = tf.zeros([3,3])
print("Zeros Tensor: ")
print(t5)

Zeros Tensor: 
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [7]:
#ones tensor
t6 = tf.ones([2,4])
print("Ones Tensor: ")
print(t6)

Ones Tensor: 
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


In [8]:
#matrix tensor
t7 = tf.constant([[2,4], [6,8], [10,12]])
print("Matrix Tensor: ")
print(t7)

Matrix Tensor: 
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)


In [9]:
#2.addition of 2D tensors
t_add = tf.add(t3, t7)
print("Added matrices t3 and t7: ")
print(t_add)

Added matrices t3 and t7: 
tf.Tensor(
[[ 3  9]
 [16 23]
 [30 37]], shape=(3, 2), dtype=int32)


In [11]:
#3.matrix operations using tensors
t8 = tf.constant([[2,4], [6,8], [10,12]])
t9 = tf.constant([[3,5], [7,9], [11,13]])
print("Matrix Tensors: ")
print(t8)
print(t9)

#a.addition
ta = tf.add(t8, t9)
print("Added matrices: ")
print(ta)

#b.subtraction
tb = tf.subtract(t8, t9)
print("Subtracted matrices: ")
print(tb)

#c.element wise multiplication
tc = tf.multiply(t8, t9)
print("Element-wise multiplied matrices: ")
print(tc)

#d.multiplication(dot product)
td = tf.matmul(t8, tf.transpose(t9))
print("Dot product of matrices: ")
print(td)

#e.transpose
te = tf.transpose(t8)
print("Transpose of matrix t8: ")
print(te)

Matrix Tensors: 
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  5]
 [ 7  9]
 [11 13]], shape=(3, 2), dtype=int32)
Added matrices: 
tf.Tensor(
[[ 5  9]
 [13 17]
 [21 25]], shape=(3, 2), dtype=int32)
Subtracted matrices: 
tf.Tensor(
[[-1 -1]
 [-1 -1]
 [-1 -1]], shape=(3, 2), dtype=int32)
Element-wise multiplied matrices: 
tf.Tensor(
[[  6  20]
 [ 42  72]
 [110 156]], shape=(3, 2), dtype=int32)
Dot product of matrices: 
tf.Tensor(
[[ 26  50  74]
 [ 58 114 170]
 [ 90 178 266]], shape=(3, 3), dtype=int32)
Transpose of matrix t8: 
tf.Tensor(
[[ 2  6 10]
 [ 4  8 12]], shape=(2, 3), dtype=int32)
